version: '3.9'

services:
  webapp:
    build: ./app
    restart: on-failure
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - webapp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
