version: '3'

tasks:
  run:api:
    dir: 'app'
    cmds:
      - go run ./main.go
  tool:swagsorter:
    cmds:
      - node ./tools/swagsorter/index.mjs
  swag:
    dir: 'app'
    cmds:
      - swag init